### ISSUE TITLE
Cannot read property debug of undefined

### ISSUE THREAD

**Issue by devotox** [fastify/fastify-compress#123]
## 🐛 Bug Report

```
TypeError: Cannot read property 'debug' of undefined
    at Object.onSend (/workspace/node_modules/fastify-compress/index.js:130:21)
    at next (/workspace/node_modules/fastify/lib/hooks.js:185:34)
    at handleResolve (/workspace/node_modules/fastify/lib/hooks.js:192:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## To Reproduce

Try to run in google cloud functions

```js
app.register(fastifyCompress, options.compress)
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *node version*: 12
- *fastify version*: >=3.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by mcollina** [comment]
Can you provide steps to reproduce?

**Comment by devotox** [comment]
I have done nothing at all. Just registered the plugin.  and trying to run it on GCP returns that error
